---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

<!--
You'll still need to render `README.Rmd` regularly, to keep `README.md` up-to-date. `devtools::build_readme()` is handy for this. You could also use GitHub Actions to re-render `README.Rmd` every time you push. An example workflow can be found here: <https://github.com/r-lib/actions/tree/v1/examples>.

You can also embed plots in R chunks. In that case, don't forget to commit and push the resulting figure files, so they display on GitHub and CRAN.
-->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# gcplyr

<!-- badges: start -->
<!-- badges: end -->

The goal of gcplyr is to facilitate manipulation and analysis of bacterial growth curves data.

gcplyr is currently in an **alpha release**. Many features are still under development and documentation may be incomplete or missing. Please send all questions, requests, and bugs to mikeblazanin@gmail.com


## What this package can do

* Bacterial density time series data is commonly generated by plate readers in a number of different formats. `gcplyr` can flexibly import all the common formats and reshape them for downstream analyses.
* Information on the experimental design elements of a set of growth curves might be saved in a tabular file (e.g. an Excel file), or may only exist non-digitally (e.g. in a lab notebook). `gcplyr` can import experimental designs from files or allow users to input that information directly through `gcplyr` functions. Then, `gcplyr` can merge these design elements with the density data imported from files.
* Growth curves datasets can be processed (e.g. smoothing) and analyzed using a variety of `gcplyr` functions

## Installation

You can install gcplyr from [GitHub](https://github.com/) with:

``` r
install.packages("devtools")
devtools::install_github("mikeblazanin/gcplyr")
```

## Getting Started

The best way to get started is to check out the `gcplyr-workflow` vignette, which included examples of all of the most common `gcplyr` functions and walks through how to import, manipulate, and analyze growth curves data using `gcplyr` from start to finish.

You can [access a pdf of the workflow vignette here](./vignettes/gcplyr-workflow.pdf "gcplyr workflow vignette")

Or, after installing `gcplyr`, run:

``` r
vignette("gcplyr-workflow")
```
