#Target journals
mSystems?
mBio?
mSphere - explicitly has a Resource Reports article type, maybe if I have to write a bunch for dissertation anyways?
Spectrum - ASM's Plos One
MRA - articles are super short like 1 page very easy to write very fast reviews
JOSS - out, not on pubmed
R Journal - out, not on pubmed
Journal of Statistical Software - out, not on pubmed
BMC Bioinformatics
Bioinformatics

#Testing
micro:  devtools::load_all() and interactively running tests
mezzo:  testthat::test_file("tests/testthat/mytest.R")
macro:  devtools::test() 
macro+: devtools::check()

rhub::check_for_cran()

#Force-installing new version to re-build vignette & check tests
R CMD build --no-build-vignettes
R CMD check --no-build-vignettes --no-tests
(run R CMD check --help for more options)
Alternatively:
  install current version with devtools::install() or Ctrl+Shift+B
  OR devtools::build_rmd("vignettes/my-vignette.Rmd")

#Every new version
1. Save & commit all changes to code
2. Re-build vignettes (see code in vignette to re-build all formats at once)
3. Commit new vignettes
4. Decide new version number, update DESCRIPTION version (dropping .9000) and date, commit
5. R CMD build gcplyr
6. R CMD check gcplyr_X.X.X.tar.gz
7. R CMD INSTALL gcplyr_X.X.X.tar.gz
8. Organize, edit, and proofread NEWS.md. Commit.
9. Re-knit README.Rmd and index.Rmd
10. Save & commit newly generated README.md file
      in bash: git commit -m "commit msg here" --no-verify
11. Push everything
12. git checkout master
13. git merge develop
14. git push
15. git checkout develop
16. Update DESCRIPTION to development version number (add .9000 at end of previous version)
17. Add new header to NEWS.md for development version number
18. Add new release on GitHub

#Releasing to CRAN
1. run process above, make sure you're back on master branch
2. run rhub::check_for_cran
3. edit cran-comments.md
4. devtools::release(args = "--compact-vignettes=gs+qpdf")

#Managing master & develop branches:
https://stackoverflow.com/questions/39478482/how-to-create-development-branch-from-master-on-github

## Creating a git develop branch
You can list all of your current branches like this:

```{bash}
git branch -a
```

This shows all of the local and remote branches. Assuming you only have a single master branch, you'd see the following:

```{bash}
* master
  remotes/origin/master
```
The * means the current branch.

To create a new branch named develop, use the following command:

```{bash}
git checkout -b develop
```

The -b flag creates the branch. Listing the branches now should show:

```{bash}
* develop
  master
  remotes/origin/master
```

## Changing branches
You shouldn't commit anything directly to the master branch. Instead do all your work on the develop branch and then merge develop into master whenever you have a new public release.

You are already in your develop branch, but if you weren't, the way to switch is as follows:

```{bash}
git checkout develop
```

That's the same way you create a branch but without the -b.

## Making changes on develop
When making changes, add and commit as usual:

```{bash}
git add .
git commit -m "whatever"
```

The first time you push to your remote do it like so:

```{bash}
git push -u origin develop
```

The -u flag stands for --set-upstream. After the first time you only need to do it like this:

```{bash}
git push
```

## Merging develop to master
Once your develop is ready to merge into master you can do it like so:

First switch to your local master branch:

```{bash}
git checkout master
```

To merge develop into master do the following:

```{bash}
git merge develop
```

Then push the changes in local master to the remote master:

```{bash}
git push
```

Done.

## Deleting a branch
If you don't need the develop branch anymore, or you just want to delete it and start over, you can do the following:

Delete the remote develop branch:

```{bash}
git push -d origin develop
```

Then delete the local branch:

```{bash}
git branch -d develop
```

The -d means delete.

# Name options:
gcplyr
growthcurvalyzer
gcanalyzer
gcer


#General pipeline:
 1.  import_blockmeasures OR
       (read_blocks -> uninterleave (optional) -> widen_blocks)
     import_widemeasures
 2.  pivot_wide_longer
 3.  make_tidydesign OR
     import_blockdesign OR
     use plater::read_plate with ONLY the design elements
 4.  merge_tidydesign_tidymeasures
 5.  [pre-process: smoothing, normalization]
 6.  [process: derivs, peak-finding, curve fitting]